### ISSUE TITLE
Line plot bug in y-axis range with continuous Y variable

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/ClinEpiWebsite#61] opened 2022-09-16 15:11 UTC
To recreate:
Use the PRISM ICEMR Cohort and create a Line plot
X- axis: Age
Y-axis: Plasmodium asexual stages, by microscopy result
Function: Arithmetic mean (the same issue exists with median and geometric mean)

The plot should use the range of the means to set the Y-axis. However, it seems to be using the range of the raw Y variable data instead. This is problematic because it makes it look like a flat line with no data variation, whereas if you toggle on the log scale for the Y axis or change the default Y-axis range, you can see a strong relationship between age and parasite density.

https://qa.restricted.clinepidb.org/analysis/XhXiciQ
<img width="1147" alt="Screen Shot 2022-09-16 at 11 09 05 AM" src="https://user-images.githubusercontent.com/54597319/190671610-676d02ae-02be-4dac-992a-56d1197f197d.png">

**Comment by danicahelb** [comment] 2022-09-16 20:39
@jernestmyers take a look at this ticket that describes the 3 options for the range (full range, auto-zoom & custom) https://github.com/VEuPathDB/web-eda/issues/1097

**Comment by danicahelb** [comment] 2022-09-19 15:37
@jernestmyers I don't know what I was looking at on Friday... data points look correct. its just the y-axis range that needs adjusting.

**Comment by moontrip** [comment] 2022-09-19 16:17
Hi @SheenaTomko @danicahelb @jernestmyers, 
Perhaps I can also take a look at this when I am working on this as a part of a new axis range control as Danica described. But I cannot reproduce the plots even with qa.restricted. It is shown to me as follows: (no filter, no log scale, no change on the axis ranges) So I wonder if you applied a sort of filter in the plot?

![lineplot1](https://user-images.githubusercontent.com/12802305/191064498-8ae9d2ee-f166-4d54-b653-d0883e2ff7dd.png)

**Comment by jernestmyers** [comment] 2022-09-19 16:19
@moontrip Happy to let you get into this while you work on the other related ticket. In order to replicate the "flat" graph, turn on binning for the x-axis.

**Comment by moontrip** [comment] 2022-09-19 16:28
@jernestmyers Thank you for your information! 👍 Yes I can see the flat range and it seems to be due to metadata-based dependent axis range. In my opinion, this can probably be resolved if the new axis range control is implemented: basically Auto-zoom option is data-based range so it would show the data more clearly with the upcoming Auto-zoom option https://github.com/VEuPathDB/web-eda/issues/1097

**Comment by moontrip** [comment] 2022-09-20 17:01
As I mentioned, this seems to be resolved by the new axis range control for the Lineplot Viz. Please see some screenshots made with the same example in this ticket 

https://github.com/VEuPathDB/web-eda/pull/1369#issuecomment-1252641654

**Closed** 2022-10-04 14:53 UTC
Labels: bug

**Comment by SheenaTomko** [comment] 2022-10-10 20:11
The new auto-zoom feature on the Y-axis takes you to the data as expected

**Comment by bobular** [comment] 2022-10-24 18:02
Just a quick note about the use of the `bug` tag here. Is it really a bug or more "undesired behaviour"?
